apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-{{ $.Values.cluster_name }}
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  sources:
  - helm:
      valueFiles:
      - values.yaml
      - values-{{ $.Values.cluster_name }}.yaml
      values: |-
        cluster_name: {{ $.Values.cluster_name }}
    path: apps
    repoURL: https://github.com/sector2000/cluster-management.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 1
        maxDuration: 20m
      limit: 60
